### ISSUE TITLE
[BUG] - After update to version 8 Numbered bookmarks does not work any more.

### ISSUE THREAD

**Issue by Jarek300** [alefragnani/vscode-numbered-bookmarks#97]
After update to version 8 Numbered bookmarks does not work any more. After pressing Ctrl-Shift-1 there is an error:

![image](https://user-images.githubusercontent.com/10242002/107912898-ab36be80-6f5f-11eb-8b1f-7da7d1f07b98.png)

The same for Ctrl-Shift-2 etc.

Reinstalling extension does not solve the problem.

**Comment by alefragnani** [comment]
Hi @Jarek300 ,

If the error is `command `X` not found`, I would say the extension _didn't activate_, and the bookmarks probably aren't visible

I would ask you:

* Did you noticed any error message while loading VS Code? 
* Run `Toggle Developer Tools` command and look at `Console` tab. Does it show any error?

If not, I would ask you to reinstall the extension, but doing the full process:

1. Uninstall the extension
2. Close all VS Code instances
3. Restart VS Code _(this full restart will guarantee the extension is totally removed)_
4. Reinstall the extension

If it still does not work, please report any error you see and reinstall a previous version, using the `Install Another Version` command, from the Extensions panel

Hope this helps

**Comment by alefragnani** [comment]
BTW, I would ask you a few details about your installation:

* Which OS are you using?
* Which VS Code release are you using?
* Which kind of project are you opening? 
  * single folder
  * multi-root workspace
  * remote
* How is defined the `saveBookmarksInProject` setting?

Thank you

**Comment by Jarek300** [comment]
Console contains errors:

[-1613399158964.log](https://github.com/alefragnani/vscode-numbered-bookmarks/files/5982070/-1613399158964.log)

abstractExtensionService.ts:718 Activating extension 'alefragnani.numbered-bookmarks' failed: Cannot read property 'uri' of undefined. 

Windows 10 20H2, VS Code 1.53.2.  I'm opening just one text file with its code-workspace.

saveBookmarksInProject is set to false.

**Comment by alefragnani** [comment]
Hm, it appears it is not finding the _active editor/document_.

* How is your workspace configured? 
  * Is it a saved workspace (`some.code-workspace`) or an untitled workspace (you added N folders to workspace, but didn’t save any).

Could you try to open a single folder window, to see if the extension activates?

Thank you

**Comment by Jarek300** [comment]
Visual Studio Code looks like this:
![image](https://user-images.githubusercontent.com/10242002/108027832-16999280-702b-11eb-9f4c-49f3342ada54.png)

Code workspace file (added txt extension to be able to upload):

[Work.code-workspace.txt](https://github.com/alefragnani/vscode-numbered-bookmarks/files/5986628/Work.code-workspace.txt)

**Comment by Jarek300** [comment]
I've updated extension to version 7.3 and it works correctly.

**Comment by alefragnani** [comment]
Hi @Jarek300 ,

It appears you have a VS Code window with _random files_ opened. I mean, no Folder or Workspace. Then, when you _upgrade_ the extension, the extension does not work anymore.

It seems similar to https://github.com/alefragnani/vscode-bookmarks/issues/395. If that's the case, (a migration issue) it should be fixed in the next update.

Hope this helps

**Comment by Jarek300** [comment]
Update 8.0.2 does not fix the problem:

![image](https://user-images.githubusercontent.com/10242002/110429512-5e03c380-80ab-11eb-85cd-65f864178471.png)
